name: 'PR Tests' 
  
on:  
  pull_request:  
    branches:  
      - staging  
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: linckon/calculator-app
  
jobs:  
  test-and-build:  
    runs-on: ubuntu-latest  
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test -Dtest="*ServiceTest"

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:pr-${{ github.event.number }} .